name: Schedule Test

on:
  workflow_dispatch:

  schedule:
    - cron: "53 13 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Schedule Test
        run: |
          echo "Schedule is working!"
          date -u